/**:
  ros__parameters:
    uav_parameters:
      mass: 2.0
      arm_length: 0.25
      num_of_arms: 4
      inertia:
        x: 0.08612
        y: 0.08962
        z: 0.16088
      moment_constant: 0.016
      thrust_constant: 8.54858e-06
      max_rotor_speed: 1000
      gravity: 9.81
      omega_to_pwm_coefficient:
        x_2: 0.001142
        x_1: 0.2273
        x_0: 914.2
      PWM_MIN: 1075
      PWM_MAX: 1950
      input_scaling: 1000
      zero_position_armed: 10
